version: "3"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    ports:
      - 3000:3000
    container_name: heroquest-bookkeeper-frontend
    networks:
      - mern-stack-net
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    ports:
      - 5000:5000
    container_name: heroquest-bookkeeper-backend
    networks:
      - mern-stack-net
    volumes:
      - ./backend/routes:/usr/app/routes
      - ./backend/models:/usr/app/models
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: heroquest-bookkeeper-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
